version: '3.9'

services:
  postgres:
    container_name: fullstack-postgres
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
    volumes:
      - database_data:/var/lib/postgresql/data

  adminer:
    container_name: fullstack-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  database_data:
